// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimplificaTerapia.Data;

#nullable disable

namespace SimplificaTerapia.Migrations
{
    [DbContext(typeof(SimplificaDbContext))]
    partial class SimplificaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimplificaTerapia.Models.Classes.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("data_consulta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("duracao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("forma_pagamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("horario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id_medico")
                        .HasColumnType("int");

                    b.Property<int?>("id_paciente")
                        .HasColumnType("int");

                    b.Property<string>("observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("plano_saude")
                        .HasColumnType("bit");

                    b.Property<string>("situacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipo_atendimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("id_medico");

                    b.HasIndex("id_paciente");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("SimplificaTerapia.Models.Classes.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("crm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("especialidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("formacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("municipio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_completo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("situacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sobre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("valor_por_hora")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("SimplificaTerapia.Models.Classes.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("contato_responsavel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idade")
                        .HasColumnType("int");

                    b.Property<string>("municipio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_completo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("num_cartao_sus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("responsavel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("situacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sobre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("SimplificaTerapia.Models.Classes.Consulta", b =>
                {
                    b.HasOne("SimplificaTerapia.Models.Classes.Medico", "med")
                        .WithMany()
                        .HasForeignKey("id_medico");

                    b.HasOne("SimplificaTerapia.Models.Classes.Paciente", "pac")
                        .WithMany()
                        .HasForeignKey("id_paciente");

                    b.Navigation("med");

                    b.Navigation("pac");
                });
#pragma warning restore 612, 618
        }
    }
}
